/**
 * Utility for generating auto-labels for recurring expenses and invoices
 * Format: "{{description}} for the month of {{month_name}}, {{current_year}}"
 */

export const getMonthName = (date: Date | string | number): string => {
  const d = typeof date === "string" ? new Date(date) : typeof date === "number" ? new Date(date) : date;
  return d.toLocaleString("en-US", { month: "long" });
};

export const generateRecurringLabel = (
  description: string,
  frequency: "weekly" | "biweekly" | "monthly" | "quarterly" | "annually" | "yearly",
  targetDate?: Date | string
): string => {
  const now = targetDate ? new Date(targetDate) : new Date();
  const year = now.getFullYear();

  // Determine the appropriate time period label
  let timePeriod = "";

  if (frequency === "monthly" || frequency === "yearly" || frequency === "annually") {
    const monthName = getMonthName(now);
    timePeriod = `the month of ${monthName}, ${year}`;
  } else if (frequency === "quarterly") {
    const quarter = Math.ceil((now.getMonth() + 1) / 3);
    timePeriod = `Q${quarter} ${year}`;
  } else if (frequency === "biweekly") {
    const week = Math.ceil(now.getDate() / 7);
    timePeriod = `week ${week} of ${year}`;
  } else if (frequency === "weekly") {
    const weekNum = Math.ceil(now.getDate() / 7);
    timePeriod = `week ${weekNum}`;
  }

  // Return formatted label
  return `${description} (Auto-generated from recurring) - for ${timePeriod}`;
};

/**
 * Clean auto-generated labels (remove the auto-generated part when displaying in lists)
 */
export const cleanRecurringLabel = (label: string): string => {
  return label.replace(" (Auto-generated from recurring)", "");
};

/**
 * Check if a label was auto-generated
 */
export const isAutoGeneratedRecurringLabel = (label: string): boolean => {
  return label.includes("(Auto-generated from recurring)");
};
