/**
 * Insert missing crm.africa features into Settings.tsx:
 * - 5 payment gateways: Pesapal, Mollie, Tap Pay, Airtel Money, MTN MoMo
 * - 5 new groups: Inventory, Services, E-Signatures, Email Marketing, Client Portal
 * - State variables, trpc queries, useEffects, renderContent cases
 * - Updated billing plans to match crm.africa pricing
 */
const fs = require("fs");
const path = require("path");
const FILE = path.join(__dirname, "client", "src", "pages", "Settings.tsx");
let src = fs.readFileSync(FILE, "utf8");
const NL = src.includes("\r\n") ? "\r\n" : "\n";

function insertAfter(marker, code) {
  const idx = src.indexOf(marker);
  if (idx === -1) { console.error("MARKER NOT FOUND:", marker.slice(0, 80)); process.exit(1); }
  const end = idx + marker.length;
  src = src.slice(0, end) + NL + code + src.slice(end);
}

function insertBefore(marker, code) {
  const idx = src.indexOf(marker);
  if (idx === -1) { console.error("MARKER NOT FOUND:", marker.slice(0, 80)); process.exit(1); }
  src = src.slice(0, idx) + code + NL + src.slice(idx);
}

function replaceOnce(marker, replacement) {
  const idx = src.indexOf(marker);
  if (idx === -1) { console.error("REPLACE MARKER NOT FOUND:", marker.slice(0, 80)); process.exit(1); }
  src = src.slice(0, idx) + replacement + src.slice(idx + marker.length);
}

// ═══════════════════════════════════════════════════════════════════════════════
// 1) NAV_GROUPS — Add 5 payment gateways after Paystack
// ═══════════════════════════════════════════════════════════════════════════════
insertAfter(
  `S("payments-paystack",     "Paystack",       "payments-paystack"),`,
  [
    `      S("payments-pesapal",    "Pesapal",        "payments-pesapal"),`,
    `      S("payments-mollie",     "Mollie Pay",     "payments-mollie"),`,
    `      S("payments-tappay",     "Tap Pay",        "payments-tappay"),`,
    `      S("payments-airtel",     "Airtel Money",   "payments-airtel"),`,
    `      S("payments-mtnmomo",    "MTN MoMo",       "payments-mtnmomo"),`,
  ].join(NL)
);

// ═══════════════════════════════════════════════════════════════════════════════
// 2) NAV_GROUPS — Add 5 new groups before "Other"
// ═══════════════════════════════════════════════════════════════════════════════
insertBefore(
  `    id: "other", label: "Other", icon: <MoreHorizontal className="h-4 w-4" />,`,
  [
    `  {`,
    `    id: "inventory", label: "Inventory", icon: <Package className="h-4 w-4" />,`,
    `    children: [`,
    `      S("inventory-general",    "General Settings",  "inventory-general"),`,
    `      S("inventory-categories", "Categories",         "inventory-categories"),`,
    `      S("inventory-stock",      "Stock Settings",     "inventory-stock"),`,
    `    ],`,
    `  },`,
    `  {`,
    `    id: "services", label: "Services & Checkout", icon: <Layout className="h-4 w-4" />,`,
    `    children: [`,
    `      S("services-general",    "General Settings",    "services-general"),`,
    `      S("services-categories", "Service Categories",   "services-categories"),`,
    `      S("services-checkout",   "Online Checkout",      "services-checkout"),`,
    `    ],`,
    `  },`,
    `  {`,
    `    id: "e-signatures", label: "E-Signatures", icon: <FileText className="h-4 w-4" />,`,
    `    children: [`,
    `      S("esign-general",   "General Settings",     "esign-general"),`,
    `      S("esign-providers", "Signature Providers",   "esign-providers"),`,
    `      S("esign-templates", "Document Templates",    "esign-templates"),`,
    `    ],`,
    `  },`,
    `  {`,
    `    id: "email-marketing", label: "Email Marketing", icon: <Mail className="h-4 w-4" />,`,
    `    children: [`,
    `      S("emarketing-general",   "General Settings",  "emarketing-general"),`,
    `      S("emarketing-campaigns", "Campaigns",          "emarketing-campaigns"),`,
    `      S("emarketing-lists",     "Mailing Lists",      "emarketing-lists"),`,
    `      S("emarketing-templates", "Templates",          "emarketing-templates"),`,
    `    ],`,
    `  },`,
    `  {`,
    `    id: "client-portal", label: "Client Portal", icon: <Globe className="h-4 w-4" />,`,
    `    children: [`,
    `      S("portal-general",     "General Settings",  "portal-general"),`,
    `      S("portal-branding",    "Branding",           "portal-branding"),`,
    `      S("portal-permissions", "Permissions",        "portal-permissions"),`,
    `      S("portal-modules",     "Module Access",      "portal-modules"),`,
    `    ],`,
    `  },`,
    `  {`,
  ].join(NL)
);

// ═══════════════════════════════════════════════════════════════════════════════
// 3) State variables — Add after paystack state
// ═══════════════════════════════════════════════════════════════════════════════
insertAfter(
  `const [paystack, setPaystack] = useState({ enabled: false, publicKey: "", secretKey: "" });`,
  [
    `  const [pesapal, setPesapal] = useState({ enabled: false, consumerKey: "", consumerSecret: "", environment: "sandbox" });`,
    `  const [mollie, setMollie] = useState({ enabled: false, apiKey: "", testMode: true });`,
    `  const [tapPay, setTapPay] = useState({ enabled: false, merchantId: "", apiKey: "", environment: "sandbox" });`,
    `  const [airtelMoney, setAirtelMoney] = useState({ enabled: false, clientId: "", clientSecret: "", environment: "sandbox" });`,
    `  const [mtnMomo, setMtnMomo] = useState({ enabled: false, subscriptionKey: "", apiUser: "", apiKey: "", environment: "sandbox" });`,
    ``,
    `  // ── Inventory ──────────────────────────────────────────────────────────────`,
    `  const [inventoryGeneral, setInventoryGeneral] = useState({ trackStock: true, lowStockThreshold: "10", autoReorder: false, defaultWarehouse: "" });`,
    `  const [inventoryCategories, setInventoryCategories] = useState<{id:string;name:string}[]>([]);`,
    `  const [newInventoryCat, setNewInventoryCat] = useState({ name: "" });`,
    `  const [inventoryStock, setInventoryStock] = useState({ method: "fifo", allowNegative: false, barcodeEnabled: false });`,
    ``,
    `  // ── Services & Checkout ────────────────────────────────────────────────────`,
    `  const [servicesGeneral, setServicesGeneral] = useState({ enabled: true, showPricing: true, allowOnlineBooking: false, bookingUrl: "" });`,
    `  const [servicesCategories, setServicesCategories] = useState<{id:string;name:string}[]>([]);`,
    `  const [newServiceCat, setNewServiceCat] = useState({ name: "" });`,
    `  const [servicesCheckout, setServicesCheckout] = useState({ enabled: false, requireLogin: true, allowGuestCheckout: false, termsUrl: "" });`,
    ``,
    `  // ── E-Signatures ──────────────────────────────────────────────────────────`,
    `  const [esignGeneral, setEsignGeneral] = useState({ enabled: false, provider: "built-in", requireAuth: true, expiryDays: "30" });`,
    `  const [esignProviders, setEsignProviders] = useState({ docusign: false, docusignApiKey: "", hellosign: false, hellosignApiKey: "" });`,
    `  const [esignTemplates, setEsignTemplates] = useState<{id:string;name:string}[]>([]);`,
    `  const [newEsignTemplate, setNewEsignTemplate] = useState({ name: "" });`,
    ``,
    `  // ── Email Marketing ───────────────────────────────────────────────────────`,
    `  const [emarketingGeneral, setEmarketingGeneral] = useState({ enabled: false, provider: "built-in", unsubscribeUrl: "", fromName: "", fromEmail: "" });`,
    `  const [emarketingLists, setEmarketingLists] = useState<{id:string;name:string}[]>([]);`,
    `  const [newEmarketingList, setNewEmarketingList] = useState({ name: "" });`,
    ``,
    `  // ── Client Portal ─────────────────────────────────────────────────────────`,
    `  const [portalGeneral, setPortalGeneral] = useState({ enabled: true, requireApproval: true, showInvoices: true, showProjects: true, showTickets: true, customDomain: "" });`,
    `  const [portalBranding, setPortalBranding] = useState({ logoUrl: "", primaryColor: "#3b82f6", welcomeMessage: "", portalTitle: "" });`,
    `  const [portalPermissions, setPortalPermissions] = useState({ viewInvoices: true, payOnline: true, createTickets: true, viewProjects: true, downloadFiles: true, viewEstimates: true });`,
    `  const [portalModules, setPortalModules] = useState({ invoices: true, estimates: true, projects: true, tickets: true, contracts: true, knowledgebase: true, announcements: true });`,
  ].join(NL)
);

// ═══════════════════════════════════════════════════════════════════════════════
// 4) trpc queries — Add after recaptchaData
// ═══════════════════════════════════════════════════════════════════════════════
insertAfter(
  `const { data: recaptchaData }       = trpc.settings.getByCategory.useQuery({ category: "recaptcha" });`,
  [
    `  // New crm.africa queries`,
    `  const { data: pesapalData }         = trpc.settings.getByCategory.useQuery({ category: "payment_pesapal" });`,
    `  const { data: mollieData }          = trpc.settings.getByCategory.useQuery({ category: "payment_mollie" });`,
    `  const { data: tapPayData }          = trpc.settings.getByCategory.useQuery({ category: "payment_tappay" });`,
    `  const { data: airtelData }          = trpc.settings.getByCategory.useQuery({ category: "payment_airtel" });`,
    `  const { data: mtnMomoData }         = trpc.settings.getByCategory.useQuery({ category: "payment_mtnmomo" });`,
    `  const { data: inventoryGenData }    = trpc.settings.getByCategory.useQuery({ category: "inventory_general" });`,
    `  const { data: inventoryCatData }    = trpc.settings.getByCategory.useQuery({ category: "inventory_categories" });`,
    `  const { data: inventoryStockData }  = trpc.settings.getByCategory.useQuery({ category: "inventory_stock" });`,
    `  const { data: servicesGenData }     = trpc.settings.getByCategory.useQuery({ category: "services_general" });`,
    `  const { data: servicesCatData }     = trpc.settings.getByCategory.useQuery({ category: "services_categories" });`,
    `  const { data: servicesCheckoutData }= trpc.settings.getByCategory.useQuery({ category: "services_checkout" });`,
    `  const { data: esignGenData }        = trpc.settings.getByCategory.useQuery({ category: "esign_general" });`,
    `  const { data: esignProvidersData }  = trpc.settings.getByCategory.useQuery({ category: "esign_providers" });`,
    `  const { data: esignTemplatesData }  = trpc.settings.getByCategory.useQuery({ category: "esign_templates" });`,
    `  const { data: emarketingGenData }   = trpc.settings.getByCategory.useQuery({ category: "emarketing_general" });`,
    `  const { data: emarketingListsData } = trpc.settings.getByCategory.useQuery({ category: "emarketing_lists" });`,
    `  const { data: portalGenData }       = trpc.settings.getByCategory.useQuery({ category: "portal_general" });`,
    `  const { data: portalBrandData }     = trpc.settings.getByCategory.useQuery({ category: "portal_branding" });`,
    `  const { data: portalPermsData }     = trpc.settings.getByCategory.useQuery({ category: "portal_permissions" });`,
    `  const { data: portalModulesData }   = trpc.settings.getByCategory.useQuery({ category: "portal_modules" });`,
  ].join(NL)
);

// ═══════════════════════════════════════════════════════════════════════════════
// 5) useEffects — Add after recaptcha useEffect
// ═══════════════════════════════════════════════════════════════════════════════
insertAfter(
  `useEffect(() => { if (recaptchaData)     setRecaptcha({ version: recaptchaData.version || "v2", siteKey: recaptchaData.siteKey || "", secretKey: recaptchaData.secretKey || "" }); }, [recaptchaData]);`,
  [
    `  // ── crm.africa effects ──`,
    `  useEffect(() => { if (pesapalData)        setPesapal({ enabled: pesapalData.enabled === "true", consumerKey: pesapalData.consumerKey || "", consumerSecret: pesapalData.consumerSecret || "", environment: pesapalData.environment || "sandbox" }); }, [pesapalData]);`,
    `  useEffect(() => { if (mollieData)         setMollie({ enabled: mollieData.enabled === "true", apiKey: mollieData.apiKey || "", testMode: mollieData.testMode !== "false" }); }, [mollieData]);`,
    `  useEffect(() => { if (tapPayData)         setTapPay({ enabled: tapPayData.enabled === "true", merchantId: tapPayData.merchantId || "", apiKey: tapPayData.apiKey || "", environment: tapPayData.environment || "sandbox" }); }, [tapPayData]);`,
    `  useEffect(() => { if (airtelData)         setAirtelMoney({ enabled: airtelData.enabled === "true", clientId: airtelData.clientId || "", clientSecret: airtelData.clientSecret || "", environment: airtelData.environment || "sandbox" }); }, [airtelData]);`,
    `  useEffect(() => { if (mtnMomoData)        setMtnMomo({ enabled: mtnMomoData.enabled === "true", subscriptionKey: mtnMomoData.subscriptionKey || "", apiUser: mtnMomoData.apiUser || "", apiKey: mtnMomoData.apiKey || "", environment: mtnMomoData.environment || "sandbox" }); }, [mtnMomoData]);`,
    `  useEffect(() => { if (inventoryGenData)   setInventoryGeneral({ trackStock: inventoryGenData.trackStock !== "false", lowStockThreshold: inventoryGenData.lowStockThreshold || "10", autoReorder: inventoryGenData.autoReorder === "true", defaultWarehouse: inventoryGenData.defaultWarehouse || "" }); }, [inventoryGenData]);`,
    `  useEffect(() => { if (inventoryCatData)   setInventoryCategories(parseList(inventoryCatData.list)); }, [inventoryCatData]);`,
    `  useEffect(() => { if (inventoryStockData) setInventoryStock({ method: inventoryStockData.method || "fifo", allowNegative: inventoryStockData.allowNegative === "true", barcodeEnabled: inventoryStockData.barcodeEnabled === "true" }); }, [inventoryStockData]);`,
    `  useEffect(() => { if (servicesGenData)    setServicesGeneral({ enabled: servicesGenData.enabled !== "false", showPricing: servicesGenData.showPricing !== "false", allowOnlineBooking: servicesGenData.allowOnlineBooking === "true", bookingUrl: servicesGenData.bookingUrl || "" }); }, [servicesGenData]);`,
    `  useEffect(() => { if (servicesCatData)    setServicesCategories(parseList(servicesCatData.list)); }, [servicesCatData]);`,
    `  useEffect(() => { if (servicesCheckoutData) setServicesCheckout({ enabled: servicesCheckoutData.enabled === "true", requireLogin: servicesCheckoutData.requireLogin !== "false", allowGuestCheckout: servicesCheckoutData.allowGuestCheckout === "true", termsUrl: servicesCheckoutData.termsUrl || "" }); }, [servicesCheckoutData]);`,
    `  useEffect(() => { if (esignGenData)       setEsignGeneral({ enabled: esignGenData.enabled === "true", provider: esignGenData.provider || "built-in", requireAuth: esignGenData.requireAuth !== "false", expiryDays: esignGenData.expiryDays || "30" }); }, [esignGenData]);`,
    `  useEffect(() => { if (esignProvidersData) setEsignProviders({ docusign: esignProvidersData.docusign === "true", docusignApiKey: esignProvidersData.docusignApiKey || "", hellosign: esignProvidersData.hellosign === "true", hellosignApiKey: esignProvidersData.hellosignApiKey || "" }); }, [esignProvidersData]);`,
    `  useEffect(() => { if (esignTemplatesData) setEsignTemplates(parseList(esignTemplatesData.list)); }, [esignTemplatesData]);`,
    `  useEffect(() => { if (emarketingGenData)  setEmarketingGeneral({ enabled: emarketingGenData.enabled === "true", provider: emarketingGenData.provider || "built-in", unsubscribeUrl: emarketingGenData.unsubscribeUrl || "", fromName: emarketingGenData.fromName || "", fromEmail: emarketingGenData.fromEmail || "" }); }, [emarketingGenData]);`,
    `  useEffect(() => { if (emarketingListsData) setEmarketingLists(parseList(emarketingListsData.list)); }, [emarketingListsData]);`,
    `  useEffect(() => { if (portalGenData)      setPortalGeneral({ enabled: portalGenData.enabled !== "false", requireApproval: portalGenData.requireApproval !== "false", showInvoices: portalGenData.showInvoices !== "false", showProjects: portalGenData.showProjects !== "false", showTickets: portalGenData.showTickets !== "false", customDomain: portalGenData.customDomain || "" }); }, [portalGenData]);`,
    `  useEffect(() => { if (portalBrandData)    setPortalBranding({ logoUrl: portalBrandData.logoUrl || "", primaryColor: portalBrandData.primaryColor || "#3b82f6", welcomeMessage: portalBrandData.welcomeMessage || "", portalTitle: portalBrandData.portalTitle || "" }); }, [portalBrandData]);`,
    `  useEffect(() => { if (portalPermsData)    setPortalPermissions({ viewInvoices: portalPermsData.viewInvoices !== "false", payOnline: portalPermsData.payOnline !== "false", createTickets: portalPermsData.createTickets !== "false", viewProjects: portalPermsData.viewProjects !== "false", downloadFiles: portalPermsData.downloadFiles !== "false", viewEstimates: portalPermsData.viewEstimates !== "false" }); }, [portalPermsData]);`,
    `  useEffect(() => { if (portalModulesData)  setPortalModules({ invoices: portalModulesData.invoices !== "false", estimates: portalModulesData.estimates !== "false", projects: portalModulesData.projects !== "false", tickets: portalModulesData.tickets !== "false", contracts: portalModulesData.contracts !== "false", knowledgebase: portalModulesData.knowledgebase !== "false", announcements: portalModulesData.announcements !== "false" }); }, [portalModulesData]);`,
  ].join(NL)
);

// ═══════════════════════════════════════════════════════════════════════════════
// 6) Update billing-plans to match crm.africa pricing
// ═══════════════════════════════════════════════════════════════════════════════
const oldPlans = `{[{ name: "Starter", price: "Free", features: ["5 Users", "1 GB Storage", "Basic Reports"] },
                { name: "Professional", price: "$29/mo", features: ["25 Users", "10 GB Storage", "Advanced Reports", "Custom Fields"] },
                { name: "Enterprise", price: "$79/mo", features: ["Unlimited Users", "50 GB Storage", "Priority Support", "API Access", "Custom Branding"] }
              ].map`;

const newPlans = `{[{ name: "Forever Free", price: "$0", features: ["2 Users", "10 Clients", "10 Projects", "Basic CRM & Invoicing", "Email Support"] },
                { name: "Kick Start", price: "$69.99/mo", features: ["29 Users", "29 Clients", "29 Projects", "Full CRM & Billing", "Payment Gateways", "Custom Fields"] },
                { name: "Thunder", price: "$99.99/mo", features: ["50 Users", "50 Clients", "50 Projects", "E-Signatures", "Email Marketing", "Priority Support", "Inventory Management"] },
                { name: "Enterprise", price: "$299/mo", features: ["Unlimited Users", "Unlimited Clients", "Unlimited Projects", "Dedicated Account Manager", "Custom Integrations", "API Access", "White Label Branding", "SLA Guarantee"] }
              ].map`;
replaceOnce(oldPlans, newPlans);

// ═══════════════════════════════════════════════════════════════════════════════
// 7) renderContent cases — Add before "default:"
// ═══════════════════════════════════════════════════════════════════════════════
const newCases = [
  ``,
  `      // ── NEW PAYMENT GATEWAYS (crm.africa) ───────────────────────────────`,
  `      case "payments-pesapal":`,
  `        return (`,
  `          <Section title="Pesapal" description="Accept payments via Pesapal (East Africa: M-Pesa, Airtel, MTN, Visa/Mastercard)">`,
  `            <div className="flex items-center justify-between mb-2"><p className="text-sm font-medium">Enable Pesapal</p><Switch checked={pesapal.enabled} onCheckedChange={(c) => setPesapal((p) => ({ ...p, enabled: c }))} /></div>`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="Consumer Key"><Input value={pesapal.consumerKey} onChange={(e) => setPesapal((p) => ({ ...p, consumerKey: e.target.value }))} placeholder="Consumer Key" /></Field>`,
  `              <Field label="Consumer Secret"><Input type="password" value={pesapal.consumerSecret} onChange={(e) => setPesapal((p) => ({ ...p, consumerSecret: e.target.value }))} placeholder="Consumer Secret" /></Field>`,
  `              <Field label="Environment">`,
  `                <Select value={pesapal.environment} onValueChange={(v) => setPesapal((p) => ({ ...p, environment: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="sandbox">Sandbox</SelectItem><SelectItem value="live">Live</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["pesapal"]} onClick={() => save("pesapal", () => updateByCategory.mutateAsync({ category: "payment_pesapal", values: { ...pesapal, enabled: String(pesapal.enabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "payments-mollie":`,
  `        return (`,
  `          <Section title="Mollie Pay" description="Accept payments via Mollie (iDEAL, Bancontact, SEPA, Credit Cards)">`,
  `            <div className="flex items-center justify-between mb-2"><p className="text-sm font-medium">Enable Mollie</p><Switch checked={mollie.enabled} onCheckedChange={(c) => setMollie((p) => ({ ...p, enabled: c }))} /></div>`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="API Key"><Input type="password" value={mollie.apiKey} onChange={(e) => setMollie((p) => ({ ...p, apiKey: e.target.value }))} placeholder="live_… or test_…" /></Field>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Test Mode</p><p className="text-xs text-muted-foreground">Use test API key for sandbox payments</p></div>`,
  `                <Switch checked={mollie.testMode} onCheckedChange={(c) => setMollie((p) => ({ ...p, testMode: c }))} /></div>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["mollie"]} onClick={() => save("mollie", () => updateByCategory.mutateAsync({ category: "payment_mollie", values: { ...mollie, enabled: String(mollie.enabled), testMode: String(mollie.testMode) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "payments-tappay":`,
  `        return (`,
  `          <Section title="Tap Pay" description="Accept payments via Tap (Middle East & North Africa)">`,
  `            <div className="flex items-center justify-between mb-2"><p className="text-sm font-medium">Enable Tap Pay</p><Switch checked={tapPay.enabled} onCheckedChange={(c) => setTapPay((p) => ({ ...p, enabled: c }))} /></div>`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="Merchant ID"><Input value={tapPay.merchantId} onChange={(e) => setTapPay((p) => ({ ...p, merchantId: e.target.value }))} placeholder="Merchant ID" /></Field>`,
  `              <Field label="API Key"><Input type="password" value={tapPay.apiKey} onChange={(e) => setTapPay((p) => ({ ...p, apiKey: e.target.value }))} placeholder="sk_live_…" /></Field>`,
  `              <Field label="Environment">`,
  `                <Select value={tapPay.environment} onValueChange={(v) => setTapPay((p) => ({ ...p, environment: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="sandbox">Sandbox</SelectItem><SelectItem value="live">Live</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["tappay"]} onClick={() => save("tappay", () => updateByCategory.mutateAsync({ category: "payment_tappay", values: { ...tapPay, enabled: String(tapPay.enabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "payments-airtel":`,
  `        return (`,
  `          <Section title="Airtel Money" description="Accept mobile money payments via Airtel (East & Central Africa)">`,
  `            <div className="flex items-center justify-between mb-2"><p className="text-sm font-medium">Enable Airtel Money</p><Switch checked={airtelMoney.enabled} onCheckedChange={(c) => setAirtelMoney((p) => ({ ...p, enabled: c }))} /></div>`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="Client ID"><Input value={airtelMoney.clientId} onChange={(e) => setAirtelMoney((p) => ({ ...p, clientId: e.target.value }))} placeholder="Client ID" /></Field>`,
  `              <Field label="Client Secret"><Input type="password" value={airtelMoney.clientSecret} onChange={(e) => setAirtelMoney((p) => ({ ...p, clientSecret: e.target.value }))} placeholder="Client Secret" /></Field>`,
  `              <Field label="Environment">`,
  `                <Select value={airtelMoney.environment} onValueChange={(v) => setAirtelMoney((p) => ({ ...p, environment: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="sandbox">Sandbox</SelectItem><SelectItem value="live">Live</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["airtel"]} onClick={() => save("airtel", () => updateByCategory.mutateAsync({ category: "payment_airtel", values: { ...airtelMoney, enabled: String(airtelMoney.enabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "payments-mtnmomo":`,
  `        return (`,
  `          <Section title="MTN Mobile Money" description="Accept mobile money via MTN MoMo (West, Central & East Africa)">`,
  `            <div className="flex items-center justify-between mb-2"><p className="text-sm font-medium">Enable MTN MoMo</p><Switch checked={mtnMomo.enabled} onCheckedChange={(c) => setMtnMomo((p) => ({ ...p, enabled: c }))} /></div>`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="Subscription Key"><Input value={mtnMomo.subscriptionKey} onChange={(e) => setMtnMomo((p) => ({ ...p, subscriptionKey: e.target.value }))} placeholder="Ocp-Apim-Subscription-Key" /></Field>`,
  `              <Field label="API User"><Input value={mtnMomo.apiUser} onChange={(e) => setMtnMomo((p) => ({ ...p, apiUser: e.target.value }))} placeholder="API User UUID" /></Field>`,
  `              <Field label="API Key"><Input type="password" value={mtnMomo.apiKey} onChange={(e) => setMtnMomo((p) => ({ ...p, apiKey: e.target.value }))} placeholder="API Key" /></Field>`,
  `              <Field label="Environment">`,
  `                <Select value={mtnMomo.environment} onValueChange={(v) => setMtnMomo((p) => ({ ...p, environment: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="sandbox">Sandbox</SelectItem><SelectItem value="live">Live</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["mtnmomo"]} onClick={() => save("mtnmomo", () => updateByCategory.mutateAsync({ category: "payment_mtnmomo", values: { ...mtnMomo, enabled: String(mtnMomo.enabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      // ── INVENTORY ───────────────────────────────────────────────────────`,
  `      case "inventory-general":`,
  `        return (`,
  `          <Section title="Inventory Settings" description="Configure inventory management for your business">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Track Stock Levels</p><p className="text-xs text-muted-foreground">Automatically track product stock quantities</p></div>`,
  `                <Switch checked={inventoryGeneral.trackStock} onCheckedChange={(v) => setInventoryGeneral((p) => ({ ...p, trackStock: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Auto-Reorder</p><p className="text-xs text-muted-foreground">Automatically create purchase orders when stock is low</p></div>`,
  `                <Switch checked={inventoryGeneral.autoReorder} onCheckedChange={(v) => setInventoryGeneral((p) => ({ ...p, autoReorder: v }))} /></div>`,
  `              <Field label="Low Stock Threshold"><Input type="number" min="1" value={inventoryGeneral.lowStockThreshold} onChange={(e) => setInventoryGeneral((p) => ({ ...p, lowStockThreshold: e.target.value }))} /></Field>`,
  `              <Field label="Default Warehouse"><Input value={inventoryGeneral.defaultWarehouse} onChange={(e) => setInventoryGeneral((p) => ({ ...p, defaultWarehouse: e.target.value }))} placeholder="Main Warehouse" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["inventory-general"]} onClick={() => save("inventory-general", () => updateByCategory.mutateAsync({ category: "inventory_general", values: { ...inventoryGeneral, trackStock: String(inventoryGeneral.trackStock), autoReorder: String(inventoryGeneral.autoReorder) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "inventory-categories":`,
  `        return (`,
  `          <Section title="Inventory Categories" description="Organize inventory items by category">`,
  `            <div className="space-y-2">{inventoryCategories.map((c) => (<div key={c.id} className="flex items-center justify-between p-2 border rounded"><span className="text-sm">{c.name}</span><button onClick={() => { const u = inventoryCategories.filter((x) => x.id !== c.id); setInventoryCategories(u); updateByCategory.mutate({ category: "inventory_categories", values: { list: JSON.stringify(u) } }); }} className="text-destructive hover:text-destructive/80"><Trash2 className="h-4 w-4" /></button></div>))}</div>`,
  `            <div className="flex gap-2 items-end mt-3"><Field label="Category Name"><Input value={newInventoryCat.name} onChange={(e) => setNewInventoryCat({ name: e.target.value })} placeholder="e.g. Electronics, Furniture" /></Field>`,
  `              <Button size="sm" onClick={() => { if (!newInventoryCat.name) { toast.error("Name required"); return; } const u = [...inventoryCategories, { id: crypto.randomUUID(), ...newInventoryCat }]; setInventoryCategories(u); setNewInventoryCat({ name: "" }); updateByCategory.mutate({ category: "inventory_categories", values: { list: JSON.stringify(u) } }); }}><Plus className="h-4 w-4 mr-1" />Add</Button></div>`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "inventory-stock":`,
  `        return (`,
  `          <Section title="Stock Settings" description="Configure stock valuation and tracking methods">`,
  `            <div className="space-y-4">`,
  `              <Field label="Valuation Method">`,
  `                <Select value={inventoryStock.method} onValueChange={(v) => setInventoryStock((p) => ({ ...p, method: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="fifo">FIFO (First In, First Out)</SelectItem><SelectItem value="lifo">LIFO (Last In, First Out)</SelectItem><SelectItem value="average">Weighted Average</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Allow Negative Stock</p><p className="text-xs text-muted-foreground">Allow selling items when stock is zero</p></div>`,
  `                <Switch checked={inventoryStock.allowNegative} onCheckedChange={(v) => setInventoryStock((p) => ({ ...p, allowNegative: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Barcode Scanning</p><p className="text-xs text-muted-foreground">Enable barcode-based stock management</p></div>`,
  `                <Switch checked={inventoryStock.barcodeEnabled} onCheckedChange={(v) => setInventoryStock((p) => ({ ...p, barcodeEnabled: v }))} /></div>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["inventory-stock"]} onClick={() => save("inventory-stock", () => updateByCategory.mutateAsync({ category: "inventory_stock", values: { ...inventoryStock, allowNegative: String(inventoryStock.allowNegative), barcodeEnabled: String(inventoryStock.barcodeEnabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      // ── SERVICES & CHECKOUT ─────────────────────────────────────────────`,
  `      case "services-general":`,
  `        return (`,
  `          <Section title="Services Settings" description="Configure service offerings and management">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Enable Services Module</p><p className="text-xs text-muted-foreground">Allow creating and selling services</p></div>`,
  `                <Switch checked={servicesGeneral.enabled} onCheckedChange={(v) => setServicesGeneral((p) => ({ ...p, enabled: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Show Pricing</p><p className="text-xs text-muted-foreground">Display service prices to clients</p></div>`,
  `                <Switch checked={servicesGeneral.showPricing} onCheckedChange={(v) => setServicesGeneral((p) => ({ ...p, showPricing: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Online Booking</p><p className="text-xs text-muted-foreground">Allow clients to book services online</p></div>`,
  `                <Switch checked={servicesGeneral.allowOnlineBooking} onCheckedChange={(v) => setServicesGeneral((p) => ({ ...p, allowOnlineBooking: v }))} /></div>`,
  `              <Field label="Booking URL"><Input value={servicesGeneral.bookingUrl} onChange={(e) => setServicesGeneral((p) => ({ ...p, bookingUrl: e.target.value }))} placeholder="https://yourdomain.com/book" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["services-general"]} onClick={() => save("services-general", () => updateByCategory.mutateAsync({ category: "services_general", values: { ...servicesGeneral, enabled: String(servicesGeneral.enabled), showPricing: String(servicesGeneral.showPricing), allowOnlineBooking: String(servicesGeneral.allowOnlineBooking) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "services-categories":`,
  `        return (`,
  `          <Section title="Service Categories" description="Organize services by category">`,
  `            <div className="space-y-2">{servicesCategories.map((c) => (<div key={c.id} className="flex items-center justify-between p-2 border rounded"><span className="text-sm">{c.name}</span><button onClick={() => { const u = servicesCategories.filter((x) => x.id !== c.id); setServicesCategories(u); updateByCategory.mutate({ category: "services_categories", values: { list: JSON.stringify(u) } }); }} className="text-destructive hover:text-destructive/80"><Trash2 className="h-4 w-4" /></button></div>))}</div>`,
  `            <div className="flex gap-2 items-end mt-3"><Field label="Category Name"><Input value={newServiceCat.name} onChange={(e) => setNewServiceCat({ name: e.target.value })} placeholder="e.g. Consulting, Maintenance" /></Field>`,
  `              <Button size="sm" onClick={() => { if (!newServiceCat.name) { toast.error("Name required"); return; } const u = [...servicesCategories, { id: crypto.randomUUID(), ...newServiceCat }]; setServicesCategories(u); setNewServiceCat({ name: "" }); updateByCategory.mutate({ category: "services_categories", values: { list: JSON.stringify(u) } }); }}><Plus className="h-4 w-4 mr-1" />Add</Button></div>`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "services-checkout":`,
  `        return (`,
  `          <Section title="Online Checkout" description="Configure online service checkout and payment collection">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Enable Checkout</p><p className="text-xs text-muted-foreground">Allow online service purchases</p></div>`,
  `                <Switch checked={servicesCheckout.enabled} onCheckedChange={(v) => setServicesCheckout((p) => ({ ...p, enabled: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Require Login</p><p className="text-xs text-muted-foreground">Require client login before checkout</p></div>`,
  `                <Switch checked={servicesCheckout.requireLogin} onCheckedChange={(v) => setServicesCheckout((p) => ({ ...p, requireLogin: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Guest Checkout</p><p className="text-xs text-muted-foreground">Allow checkout without an account</p></div>`,
  `                <Switch checked={servicesCheckout.allowGuestCheckout} onCheckedChange={(v) => setServicesCheckout((p) => ({ ...p, allowGuestCheckout: v }))} /></div>`,
  `              <Field label="Terms & Conditions URL"><Input value={servicesCheckout.termsUrl} onChange={(e) => setServicesCheckout((p) => ({ ...p, termsUrl: e.target.value }))} placeholder="https://yourdomain.com/terms" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["services-checkout"]} onClick={() => save("services-checkout", () => updateByCategory.mutateAsync({ category: "services_checkout", values: { ...servicesCheckout, enabled: String(servicesCheckout.enabled), requireLogin: String(servicesCheckout.requireLogin), allowGuestCheckout: String(servicesCheckout.allowGuestCheckout) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      // ── E-SIGNATURES ───────────────────────────────────────────────────`,
  `      case "esign-general":`,
  `        return (`,
  `          <Section title="E-Signature Settings" description="Configure electronic signature capabilities for contracts and proposals">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Enable E-Signatures</p><p className="text-xs text-muted-foreground">Allow electronic document signing</p></div>`,
  `                <Switch checked={esignGeneral.enabled} onCheckedChange={(v) => setEsignGeneral((p) => ({ ...p, enabled: v }))} /></div>`,
  `              <Field label="Provider">`,
  `                <Select value={esignGeneral.provider} onValueChange={(v) => setEsignGeneral((p) => ({ ...p, provider: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="built-in">Built-in</SelectItem><SelectItem value="docusign">DocuSign</SelectItem><SelectItem value="hellosign">HelloSign</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Require Authentication</p><p className="text-xs text-muted-foreground">Signers must verify identity before signing</p></div>`,
  `                <Switch checked={esignGeneral.requireAuth} onCheckedChange={(v) => setEsignGeneral((p) => ({ ...p, requireAuth: v }))} /></div>`,
  `              <Field label="Signature Expiry (days)"><Input type="number" min="1" value={esignGeneral.expiryDays} onChange={(e) => setEsignGeneral((p) => ({ ...p, expiryDays: e.target.value }))} /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["esign-general"]} onClick={() => save("esign-general", () => updateByCategory.mutateAsync({ category: "esign_general", values: { ...esignGeneral, enabled: String(esignGeneral.enabled), requireAuth: String(esignGeneral.requireAuth) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "esign-providers":`,
  `        return (`,
  `          <Section title="Signature Providers" description="Configure third-party e-signature integrations">`,
  `            <div className="space-y-6">`,
  `              <div className="border rounded-lg p-4 space-y-3">`,
  `                <div className="flex items-center justify-between"><p className="font-medium">DocuSign</p><Switch checked={esignProviders.docusign} onCheckedChange={(v) => setEsignProviders((p) => ({ ...p, docusign: v }))} /></div>`,
  `                {esignProviders.docusign && <Field label="Integration Key"><Input type="password" value={esignProviders.docusignApiKey} onChange={(e) => setEsignProviders((p) => ({ ...p, docusignApiKey: e.target.value }))} placeholder="DocuSign Integration Key" /></Field>}`,
  `              </div>`,
  `              <div className="border rounded-lg p-4 space-y-3">`,
  `                <div className="flex items-center justify-between"><p className="font-medium">HelloSign</p><Switch checked={esignProviders.hellosign} onCheckedChange={(v) => setEsignProviders((p) => ({ ...p, hellosign: v }))} /></div>`,
  `                {esignProviders.hellosign && <Field label="API Key"><Input type="password" value={esignProviders.hellosignApiKey} onChange={(e) => setEsignProviders((p) => ({ ...p, hellosignApiKey: e.target.value }))} placeholder="HelloSign API Key" /></Field>}`,
  `              </div>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["esign-providers"]} onClick={() => save("esign-providers", () => updateByCategory.mutateAsync({ category: "esign_providers", values: { ...esignProviders, docusign: String(esignProviders.docusign), hellosign: String(esignProviders.hellosign) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "esign-templates":`,
  `        return (`,
  `          <Section title="Document Templates" description="Manage reusable document templates for e-signatures">`,
  `            <div className="space-y-2">{esignTemplates.map((t) => (<div key={t.id} className="flex items-center justify-between p-2 border rounded"><span className="text-sm">{t.name}</span><button onClick={() => { const u = esignTemplates.filter((x) => x.id !== t.id); setEsignTemplates(u); updateByCategory.mutate({ category: "esign_templates", values: { list: JSON.stringify(u) } }); }} className="text-destructive hover:text-destructive/80"><Trash2 className="h-4 w-4" /></button></div>))}</div>`,
  `            <div className="flex gap-2 items-end mt-3"><Field label="Template Name"><Input value={newEsignTemplate.name} onChange={(e) => setNewEsignTemplate({ name: e.target.value })} placeholder="e.g. NDA, Service Agreement" /></Field>`,
  `              <Button size="sm" onClick={() => { if (!newEsignTemplate.name) { toast.error("Name required"); return; } const u = [...esignTemplates, { id: crypto.randomUUID(), ...newEsignTemplate }]; setEsignTemplates(u); setNewEsignTemplate({ name: "" }); updateByCategory.mutate({ category: "esign_templates", values: { list: JSON.stringify(u) } }); }}><Plus className="h-4 w-4 mr-1" />Add</Button></div>`,
  `          </Section>`,
  `        );`,
  ``,
  `      // ── EMAIL MARKETING ────────────────────────────────────────────────`,
  `      case "emarketing-general":`,
  `        return (`,
  `          <Section title="Email Marketing Settings" description="Configure email marketing campaigns and automation">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Enable Email Marketing</p><p className="text-xs text-muted-foreground">Send newsletters and marketing campaigns</p></div>`,
  `                <Switch checked={emarketingGeneral.enabled} onCheckedChange={(v) => setEmarketingGeneral((p) => ({ ...p, enabled: v }))} /></div>`,
  `              <Field label="Provider">`,
  `                <Select value={emarketingGeneral.provider} onValueChange={(v) => setEmarketingGeneral((p) => ({ ...p, provider: v }))}>`,
  `                  <SelectTrigger><SelectValue /></SelectTrigger>`,
  `                  <SelectContent><SelectItem value="built-in">Built-in</SelectItem><SelectItem value="mailchimp">Mailchimp</SelectItem><SelectItem value="sendinblue">Sendinblue</SelectItem><SelectItem value="sendgrid">SendGrid</SelectItem></SelectContent>`,
  `                </Select>`,
  `              </Field>`,
  `              <Field label="From Name"><Input value={emarketingGeneral.fromName} onChange={(e) => setEmarketingGeneral((p) => ({ ...p, fromName: e.target.value }))} placeholder="Your Company" /></Field>`,
  `              <Field label="From Email"><Input type="email" value={emarketingGeneral.fromEmail} onChange={(e) => setEmarketingGeneral((p) => ({ ...p, fromEmail: e.target.value }))} placeholder="marketing@yourdomain.com" /></Field>`,
  `              <Field label="Unsubscribe URL"><Input value={emarketingGeneral.unsubscribeUrl} onChange={(e) => setEmarketingGeneral((p) => ({ ...p, unsubscribeUrl: e.target.value }))} placeholder="https://yourdomain.com/unsubscribe" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["emarketing-general"]} onClick={() => save("emarketing-general", () => updateByCategory.mutateAsync({ category: "emarketing_general", values: { ...emarketingGeneral, enabled: String(emarketingGeneral.enabled) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "emarketing-campaigns":`,
  `        return (`,
  `          <Section title="Campaigns" description="Create and manage email marketing campaigns">`,
  `            <p className="text-sm text-muted-foreground mb-3">Build targeted email campaigns for your clients and leads.</p>`,
  `            <div className="space-y-2">`,
  `              {["Welcome Series", "Monthly Newsletter", "Product Announcements", "Re-engagement"].map((name) => (`,
  `                <div key={name} className="flex items-center justify-between p-3 border rounded-md hover:bg-muted/50">`,
  `                  <div><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">Template campaign</p></div>`,
  `                  <div className="flex gap-2"><Badge variant="secondary">Draft</Badge><Button variant="outline" size="sm">Edit</Button></div>`,
  `                </div>`,
  `              ))}`,
  `            </div>`,
  `            <Button className="mt-4"><Plus className="h-4 w-4 mr-1" />Create Campaign</Button>`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "emarketing-lists":`,
  `        return (`,
  `          <Section title="Mailing Lists" description="Manage subscriber lists for email campaigns">`,
  `            <div className="space-y-2">{emarketingLists.map((l) => (<div key={l.id} className="flex items-center justify-between p-2 border rounded"><span className="text-sm">{l.name}</span><button onClick={() => { const u = emarketingLists.filter((x) => x.id !== l.id); setEmarketingLists(u); updateByCategory.mutate({ category: "emarketing_lists", values: { list: JSON.stringify(u) } }); }} className="text-destructive hover:text-destructive/80"><Trash2 className="h-4 w-4" /></button></div>))}</div>`,
  `            <div className="flex gap-2 items-end mt-3"><Field label="List Name"><Input value={newEmarketingList.name} onChange={(e) => setNewEmarketingList({ name: e.target.value })} placeholder="e.g. Newsletter, Product Updates" /></Field>`,
  `              <Button size="sm" onClick={() => { if (!newEmarketingList.name) { toast.error("Name required"); return; } const u = [...emarketingLists, { id: crypto.randomUUID(), ...newEmarketingList }]; setEmarketingLists(u); setNewEmarketingList({ name: "" }); updateByCategory.mutate({ category: "emarketing_lists", values: { list: JSON.stringify(u) } }); }}><Plus className="h-4 w-4 mr-1" />Add</Button></div>`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "emarketing-templates":`,
  `        return (`,
  `          <Section title="Marketing Templates" description="Design reusable email templates for campaigns">`,
  `            <div className="space-y-2">`,
  `              {["Welcome Email", "Product Launch", "Event Invitation", "Monthly Digest", "Special Offer"].map((name) => (`,
  `                <div key={name} className="flex items-center justify-between p-3 border rounded-md hover:bg-muted/50">`,
  `                  <div><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">HTML Email Template</p></div>`,
  `                  <Button variant="outline" size="sm">Customize</Button>`,
  `                </div>`,
  `              ))}`,
  `            </div>`,
  `            <Button className="mt-4"><Plus className="h-4 w-4 mr-1" />Create Template</Button>`,
  `          </Section>`,
  `        );`,
  ``,
  `      // ── CLIENT PORTAL ──────────────────────────────────────────────────`,
  `      case "portal-general":`,
  `        return (`,
  `          <Section title="Client Portal Settings" description="Configure the client-facing portal experience">`,
  `            <div className="space-y-4">`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Enable Client Portal</p><p className="text-xs text-muted-foreground">Allow clients to access their portal</p></div>`,
  `                <Switch checked={portalGeneral.enabled} onCheckedChange={(v) => setPortalGeneral((p) => ({ ...p, enabled: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Require Approval</p><p className="text-xs text-muted-foreground">Admin must approve client portal registrations</p></div>`,
  `                <Switch checked={portalGeneral.requireApproval} onCheckedChange={(v) => setPortalGeneral((p) => ({ ...p, requireApproval: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Show Invoices</p><p className="text-xs text-muted-foreground">Clients can view their invoices</p></div>`,
  `                <Switch checked={portalGeneral.showInvoices} onCheckedChange={(v) => setPortalGeneral((p) => ({ ...p, showInvoices: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Show Projects</p><p className="text-xs text-muted-foreground">Clients can view their project status</p></div>`,
  `                <Switch checked={portalGeneral.showProjects} onCheckedChange={(v) => setPortalGeneral((p) => ({ ...p, showProjects: v }))} /></div>`,
  `              <div className="flex items-center justify-between"><div><p className="text-sm font-medium">Show Tickets</p><p className="text-xs text-muted-foreground">Clients can view and create support tickets</p></div>`,
  `                <Switch checked={portalGeneral.showTickets} onCheckedChange={(v) => setPortalGeneral((p) => ({ ...p, showTickets: v }))} /></div>`,
  `              <Field label="Custom Domain"><Input value={portalGeneral.customDomain} onChange={(e) => setPortalGeneral((p) => ({ ...p, customDomain: e.target.value }))} placeholder="portal.yourdomain.com" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["portal-general"]} onClick={() => save("portal-general", () => updateByCategory.mutateAsync({ category: "portal_general", values: { ...portalGeneral, enabled: String(portalGeneral.enabled), requireApproval: String(portalGeneral.requireApproval), showInvoices: String(portalGeneral.showInvoices), showProjects: String(portalGeneral.showProjects), showTickets: String(portalGeneral.showTickets) } }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "portal-branding":`,
  `        return (`,
  `          <Section title="Portal Branding" description="Customize the look and feel of your client portal">`,
  `            <div className="grid grid-cols-1 gap-4">`,
  `              <Field label="Portal Title"><Input value={portalBranding.portalTitle} onChange={(e) => setPortalBranding((p) => ({ ...p, portalTitle: e.target.value }))} placeholder="Client Portal" /></Field>`,
  `              <Field label="Logo URL"><Input value={portalBranding.logoUrl} onChange={(e) => setPortalBranding((p) => ({ ...p, logoUrl: e.target.value }))} placeholder="https://yourdomain.com/logo.png" /></Field>`,
  `              <Field label="Primary Color"><div className="flex gap-2"><Input value={portalBranding.primaryColor} onChange={(e) => setPortalBranding((p) => ({ ...p, primaryColor: e.target.value }))} /><input type="color" value={portalBranding.primaryColor} onChange={(e) => setPortalBranding((p) => ({ ...p, primaryColor: e.target.value }))} className="w-10 h-10 rounded border cursor-pointer" /></div></Field>`,
  `              <Field label="Welcome Message"><Input value={portalBranding.welcomeMessage} onChange={(e) => setPortalBranding((p) => ({ ...p, welcomeMessage: e.target.value }))} placeholder="Welcome to your client portal" /></Field>`,
  `            </div>`,
  `            <SaveButton saving={!!saving["portal-branding"]} onClick={() => save("portal-branding", () => updateByCategory.mutateAsync({ category: "portal_branding", values: portalBranding }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "portal-permissions":`,
  `        return (`,
  `          <Section title="Portal Permissions" description="Control what clients can do in the portal">`,
  `            <div className="space-y-4">`,
  `              {Object.entries({ viewInvoices: "View Invoices", payOnline: "Pay Online", createTickets: "Create Support Tickets", viewProjects: "View Projects", downloadFiles: "Download Files", viewEstimates: "View Estimates" }).map(([key, label]) => (`,
  `                <div key={key} className="flex items-center justify-between"><p className="text-sm font-medium">{label}</p><Switch checked={(portalPermissions as any)[key]} onCheckedChange={(v) => setPortalPermissions((p) => ({ ...p, [key]: v }))} /></div>`,
  `              ))}`,
  `            </div>`,
  `            <SaveButton saving={!!saving["portal-permissions"]} onClick={() => save("portal-permissions", () => updateByCategory.mutateAsync({ category: "portal_permissions", values: Object.fromEntries(Object.entries(portalPermissions).map(([k, v]) => [k, String(v)])) }))} />`,
  `          </Section>`,
  `        );`,
  ``,
  `      case "portal-modules":`,
  `        return (`,
  `          <Section title="Module Access" description="Control which modules are visible in the client portal">`,
  `            <div className="space-y-4">`,
  `              {Object.entries({ invoices: "Invoices", estimates: "Estimates", projects: "Projects", tickets: "Support Tickets", contracts: "Contracts", knowledgebase: "Knowledge Base", announcements: "Announcements" }).map(([key, label]) => (`,
  `                <div key={key} className="flex items-center justify-between"><p className="text-sm font-medium">{label}</p><Switch checked={(portalModules as any)[key]} onCheckedChange={(v) => setPortalModules((p) => ({ ...p, [key]: v }))} /></div>`,
  `              ))}`,
  `            </div>`,
  `            <SaveButton saving={!!saving["portal-modules"]} onClick={() => save("portal-modules", () => updateByCategory.mutateAsync({ category: "portal_modules", values: Object.fromEntries(Object.entries(portalModules).map(([k, v]) => [k, String(v)])) }))} />`,
  `          </Section>`,
  `        );`,
].join(NL);

insertBefore(`      default:`, newCases);

// ═══════════════════════════════════════════════════════════════════════════════
// 8) Update billing-plans grid from 3 to 4 columns
// ═══════════════════════════════════════════════════════════════════════════════
replaceOnce(
  `<div className="grid grid-cols-3 gap-4">`,
  `<div className="grid grid-cols-2 md:grid-cols-4 gap-4">`
);

// ═══════════════════════════════════════════════════════════════════════════════
// Write
// ═══════════════════════════════════════════════════════════════════════════════
fs.writeFileSync(FILE, src, "utf8");
const lines = src.split("\n").length;
console.log(`\n✅ Settings.tsx updated: ${lines} lines`);
console.log("Added: 5 payment gateways, 5 new groups, state vars, queries, effects, renderContent cases");
console.log("Updated: billing plans to crm.africa pricing (4 tiers), grid cols 3→4");
