$iconMap = @{
  'client\src\pages\Account.tsx' = @('User')
  'client\src\pages\Accounting.tsx' = @('CreditCard')
  'client\src\pages\Activity.tsx' = @('Activity')
  'client\src\pages\AllowancesManagement.tsx' = @('DollarSign')
  'client\src\pages\AndroidApp.tsx' = @('Smartphone')
  'client\src\pages\AnomalyDetection.tsx' = @('AlertTriangle')
  'client\src\pages\ApiDocumentation.tsx' = @('BookOpen')
  'client\src\pages\Approvals.tsx' = @('CheckCircle')
  'client\src\pages\AssetManagement.tsx' = @('Package')
  'client\src\pages\Attendance.tsx' = @('Clock')
  'client\src\pages\BackupManagement.tsx' = @('Database')
  'client\src\pages\BankReconciliation.tsx' = @('CreditCard')
  'client\src\pages\BillingDashboard.tsx' = @('BarChart3')
  'client\src\pages\BiTools.tsx' = @('BarChart3')
  'client\src\pages\Budgets.tsx' = @('PiggyBank')
  'client\src\pages\BulkOperations.tsx' = @('AlertCircle')
  'client\src\pages\CacheManager.tsx' = @('Database')
  'client\src\pages\ChartOfAccounts.tsx' = @('BookOpen')
  'client\src\pages\ChatbotAgent.tsx' = @('MessageSquare')
  'client\src\pages\ChurnPrediction.tsx' = @('TrendingDown')
  'client\src\pages\ClientPerformance.tsx' = @('TrendingUp')
  'client\src\pages\Clients.tsx' = @('Users')
  'client\src\pages\CohortAnalysis.tsx' = @('Users')
  'client\src\pages\Communications.tsx' = @('MessageSquare')
  'client\src\pages\ComplianceManagement.tsx' = @('Shield')
  'client\src\pages\ComponentLibrary.tsx' = @('LayoutGrid')
  'client\src\pages\ComponentShowcase.tsx' = @('LayoutGrid')
  'client\src\pages\Contacts.tsx' = @('Users')
  'client\src\pages\ContractManagement.tsx' = @('FileText')
  'client\src\pages\ConversionAnalytics.tsx' = @('TrendingUp')
  'client\src\pages\CreateAllowance.tsx' = @('Percent')
  'client\src\pages\CreateAttendance.tsx' = @('Clock')
  'client\src\pages\CreateBenefit.tsx' = @('Heart')
  'client\src\pages\CreateBudget.tsx' = @('PiggyBank')
  'client\src\pages\CreateDeduction.tsx' = @('Minus')
  'client\src\pages\CreateDepartment.tsx' = @('Building2')
  'client\src\pages\CreateEmployee.tsx' = @('Users')
  'client\src\pages\CreateExpense.tsx' = @('Receipt')
  'client\src\pages\CreateLeaveRequest.tsx' = @('Calendar')
  'client\src\pages\CreateOpportunity.tsx' = @('TrendingUp')
  'client\src\pages\CreatePayment.tsx' = @('DollarSign')
  'client\src\pages\CreatePayroll.tsx' = @('Calculator')
  'client\src\pages\CreateProduct.tsx' = @('Package')
  'client\src\pages\CreateSalaryStructure.tsx' = @('DollarSign')
  'client\src\pages\CreateService.tsx' = @('Briefcase')
  'client\src\pages\CurrencyConverter.tsx' = @('DollarSign')
  'client\src\pages\CustomReportBuilder.tsx' = @('FileText')
  'client\src\pages\DarkMode.tsx' = @('Moon')
  'client\src\pages\DatabaseTuning.tsx' = @('Database')
  'client\src\pages\DataWarehouse.tsx' = @('Database')
  'client\src\pages\DealRegistry.tsx' = @('FileText')
  'client\src\pages\DeductionsManagement.tsx' = @('Minus')
  'client\src\pages\DeliveryNotes.tsx' = @('Package')
  'client\src\pages\DeliveryTracking.tsx' = @('Truck')
  'client\src\pages\Demo.tsx' = @('BarChart3')
  'client\src\pages\Departments.tsx' = @('Building2')
  'client\src\pages\DesignSystem.tsx' = @('Palette')
  'client\src\pages\DockerOrchestration.tsx' = @('Server')
  'client\src\pages\Documentation.tsx' = @('BookOpen')
  'client\src\pages\DocumentLibrary.tsx' = @('FileText')
  'client\src\pages\EditAttendance.tsx' = @('Clock')
  'client\src\pages\EditBankReconciliation.tsx' = @('Building')
  'client\src\pages\EditBudget.tsx' = @('PiggyBank')
  'client\src\pages\EditChartOfAccounts.tsx' = @('BookOpen')
  'client\src\pages\EditDepartment.tsx' = @('Building2')
  'client\src\pages\EditEmployee.tsx' = @('Users')
  'client\src\pages\EditExpense.tsx' = @('Receipt')
  'client\src\pages\EditLeave.tsx' = @('Calendar')
  'client\src\pages\EditLPO.tsx' = @('FileText')
  'client\src\pages\EditOpportunity.tsx' = @('TrendingUp')
  'client\src\pages\EditPayment.tsx' = @('DollarSign')
  'client\src\pages\EditPayroll.tsx' = @('DollarSign')
  'client\src\pages\EditProduct.tsx' = @('Package')
  'client\src\pages\EditProject.tsx' = @('Briefcase')
  'client\src\pages\EditProposal.tsx' = @('FileText')
  'client\src\pages\EditService.tsx' = @('Briefcase')
  'client\src\pages\EmailQueue.tsx' = @('Mail')
  'client\src\pages\Employees.tsx' = @('Users')
  'client\src\pages\Encryption.tsx' = @('Lock')
  'client\src\pages\EnhancedReceiptManagement.tsx' = @('Receipt')
  'client\src\pages\Estimates.tsx' = @('FileText')
  'client\src\pages\EtlMonitor.tsx' = @('Activity')
  'client\src\pages\Expenses.tsx' = @('DollarSign')
  'client\src\pages\FeatureFlags.tsx' = @('Flag')
  'client\src\pages\FinancialDashboard.tsx' = @('BarChart3')
  'client\src\pages\FunnelAnalysis.tsx' = @('Filter')
  'client\src\pages\GRN.tsx' = @('Box')
  'client\src\pages\GRNManagement.tsx' = @('Package')
  'client\src\pages\Home.tsx' = @('FolderKanban')
  'client\src\pages\HR.tsx' = @('Users')
  'client\src\pages\HRAnalyticsPage.tsx' = @('BarChart3')
  'client\src\pages\HRModule.tsx' = @('UserCog')
  'client\src\pages\HRPayrollManagement.tsx' = @('DollarSign')
  'client\src\pages\Imprests.tsx' = @('Wallet')
  'client\src\pages\Integrations.tsx' = @('Plug')
  'client\src\pages\Internationalization.tsx' = @('Globe')
  'client\src\pages\IosApp.tsx' = @('Smartphone')
  'client\src\pages\JobGroups.tsx' = @('Building2')
  'client\src\pages\KenyanPayrollCalculator.tsx' = @('Calculator')
  'client\src\pages\LeaveManagement.tsx' = @('Calendar')
  'client\src\pages\LPOs.tsx' = @('ShoppingCart')
  'client\src\pages\LPOsEnhanced.tsx' = @('ShoppingCart')
  'client\src\pages\Messages.tsx' = @('MessageSquare')
  'client\src\pages\MicroservicesConfig.tsx' = @('Settings')
  'client\src\pages\NlpProcessor.tsx' = @('Brain')
  'client\src\pages\Notifications.tsx' = @('Bell')
  'client\src\pages\OfflineSync.tsx' = @('RefreshCw')
  'client\src\pages\Opportunities.tsx' = @('TrendingUp')
  'client\src\pages\Orders.tsx' = @('Package')
  'client\src\pages\Payments.tsx' = @('DollarSign')
  'client\src\pages\Payroll.tsx' = @('DollarSign')
  'client\src\pages\PayrollAnalytics.tsx' = @('BarChart3')
  'client\src\pages\PayrollApprovals.tsx' = @('CheckCircle2')
  'client\src\pages\PayrollProcessing.tsx' = @('Play')
  'client\src\pages\PenTesting.tsx' = @('Shield')
  'client\src\pages\Procurement.tsx' = @('ShoppingCart')
  'client\src\pages\ProcurementManagement.tsx' = @('ShoppingCart')
  'client\src\pages\ProcurementMaster.tsx' = @('ShoppingCart')
  'client\src\pages\Products.tsx' = @('Package')
  'client\src\pages\Projects.tsx' = @('Briefcase')
  'client\src\pages\Quotations.tsx' = @('FileText')
  'client\src\pages\Receipts.tsx' = @('Receipt')
  'client\src\pages\Reports.tsx' = @('TrendingUp')
  'client\src\pages\RevenueForecasting.tsx' = @('TrendingUp')
  'client\src\pages\Roles.tsx' = @('Shield')
  'client\src\pages\Sales.tsx' = @('TrendingUp')
  'client\src\pages\SchedulerDashboard.tsx' = @('Clock')
  'client\src\pages\Search.tsx' = @('Search')
  'client\src\pages\Services.tsx' = @('Wrench')
  'client\src\pages\ServiceTemplates.tsx' = @('Eye', 'TrendingUp')
  'client\src\pages\Settings.tsx' = @('Settings')
  'client\src\pages\SmsQueue.tsx' = @('MessageSquare')
  'client\src\pages\Suppliers.tsx' = @('Truck')
  'client\src\pages\SystemHealth.tsx' = @('Activity')
  'client\src\pages\TestPDFGeneration.tsx' = @('FileText')
  'client\src\pages\ThreatDetection.tsx' = @('ShieldAlert')
  'client\src\pages\Tickets.tsx' = @('Ticket')
  'client\src\pages\TimeTracking.tsx' = @('Clock')
  'client\src\pages\Tools.tsx' = @('Settings')
  'client\src\pages\tools\BrandCustomization.tsx' = @('Palette')
  'client\src\pages\tools\CustomHomepageBuilder.tsx' = @('Layout')
  'client\src\pages\tools\IntegrationGuides.tsx' = @('BookOpen')
  'client\src\pages\tools\Permissions.tsx' = @('Lock')
  'client\src\pages\tools\SystemSettings.tsx' = @('Settings')
  'client\src\pages\tools\ThemeCustomization.tsx' = @('Palette')
  'client\src\pages\TroubleshootingGuide.tsx' = @('AlertCircle')
  'client\src\pages\UsageMetering.tsx' = @('Gauge')
  'client\src\pages\UserGuide.tsx' = @('HelpCircle')
  'client\src\pages\VersionControl.tsx' = @('GitBranch')
  'client\src\pages\VulnerabilityScan.tsx' = @('Search')
  'client\src\pages\WarrantyManagement.tsx' = @('Shield')
  'client\src\pages\Webhooks.tsx' = @('Webhook')
  'client\src\pages\WorkflowAutomation.tsx' = @('Zap')
}

$fixed = 0
$skipped = 0

foreach ($relPath in $iconMap.Keys) {
  $file = Join-Path 'e:\melitech_crm' $relPath
  if (-not (Test-Path $file)) { Write-Output "MISSING: $relPath"; $skipped++; continue }
  
  $content = Get-Content $file -Raw -Encoding UTF8
  $icons = $iconMap[$relPath]
  $missing = @()
  foreach ($icon in $icons) {
    # Check if icon is already imported (either in lucide-react import or any import)
    if ($content -notmatch "\b$icon\b.*from 'lucide-react'" -and $content -notmatch "from 'lucide-react'.*\b$icon\b") {
      $missing += $icon
    }
  }
  if ($missing.Count -eq 0) { $skipped++; continue }
  
  # Check if there's already a lucide-react import to extend
  if ($content -match "import \{([^}]+)\} from 'lucide-react'") {
    $existingImport = $matches[0]
    $existing = $matches[1].Trim()
    # Add missing icons, deduplicating
    $allIcons = ($existing -split '\s*,\s*' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }) + $missing | Select-Object -Unique | Sort-Object
    $newImport = "import { $($allIcons -join ', ') } from 'lucide-react'"
    $content = $content.Replace($existingImport, $newImport)
  } else {
    # Add new import line after the last import
    $iconStr = $missing -join ', '
    $newImportLine = "import { $iconStr } from 'lucide-react';"
    # Insert after first import line
    $content = [regex]::Replace($content, "(^import [^\n]+\n)", "`$1$newImportLine`n", [System.Text.RegularExpressions.RegexOptions]::Multiline)
  }
  
  [System.IO.File]::WriteAllText($file, $content, [System.Text.Encoding]::UTF8)
  Write-Output "FIXED: $relPath (+$($missing -join ', '))"
  $fixed++
}

Write-Output "`nDone: $fixed fixed, $skipped skipped"
