-- =====================================================
-- COMPREHENSIVE SCHEMA SYNC: Add missing columns to all tables
-- Uses IF NOT EXISTS (MariaDB 10.11.16 supported)
-- =====================================================

-- === CLIENTS TABLE ===
ALTER TABLE clients ADD COLUMN IF NOT EXISTS secondaryPhone VARCHAR(50) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS bankAccountNumber VARCHAR(100) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS leadSource VARCHAR(100) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT NULL;

-- === INVOICES TABLE ===
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS estimateId VARCHAR(64) DEFAULT NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paymentPlanId VARCHAR(64) DEFAULT NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS isAutoRecurring TINYINT DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS recurringInvoiceId VARCHAR(64) DEFAULT NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS clientSubscriptionId VARCHAR(64) DEFAULT NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS discountAmount INT DEFAULT 0;

-- === EXPENSES TABLE ===
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expenseNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receiptUrl VARCHAR(500) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS accountId VARCHAR(64) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS budgetAllocationId VARCHAR(64) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approvedBy VARCHAR(64) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approvedAt TIMESTAMP NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS chartOfAccountId VARCHAR(64) DEFAULT NULL;

-- === PROJECTS TABLE ===
ALTER TABLE projects ADD COLUMN IF NOT EXISTS projectNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS actualStartDate DATETIME DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS actualEndDate DATETIME DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS actualCost INT DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS projectManager VARCHAR(64) DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tags TEXT DEFAULT NULL;

-- === PAYMENTS TABLE ===
ALTER TABLE payments ADD COLUMN IF NOT EXISTS accountId VARCHAR(64) DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS chartOfAccountType ENUM('debit','credit') DEFAULT 'debit';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS approvedBy VARCHAR(64) DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS approvedAt TIMESTAMP NULL;

-- === EMPLOYEES TABLE ===
ALTER TABLE employees ADD COLUMN IF NOT EXISTS userId VARCHAR(64) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS gender ENUM('male','female','other') DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS maritalStatus ENUM('single','married','divorced','widowed') DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS dateOfBirth DATETIME DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS probationEndDate DATETIME DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS contractEndDate DATETIME DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergencyContactName VARCHAR(255) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergencyContactRelationship VARCHAR(100) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergencyContactPhone VARCHAR(50) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergencyContact TEXT DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS bankBranch VARCHAR(255) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nhifNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nssfNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nationalId VARCHAR(100) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS photoUrl VARCHAR(500) DEFAULT NULL;

-- === TICKETS TABLE ===
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS ticketNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS resolution TEXT DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS solutionUrl VARCHAR(500) DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS attachments TEXT DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS relatedTickets TEXT DEFAULT NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS firstResponseAt TIMESTAMP NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS resolvedAt TIMESTAMP NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS closedAt TIMESTAMP NULL;

-- === WORK ORDERS TABLE ===
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS workOrderNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS issueDate TIMESTAMP NULL;
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS targetEndDate DATETIME DEFAULT NULL;
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS laborCost INT DEFAULT NULL;
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS serviceCost INT DEFAULT NULL;
ALTER TABLE workOrders ADD COLUMN IF NOT EXISTS total INT DEFAULT NULL;

-- === BUDGETS TABLE ===
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS budgetName VARCHAR(255) DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS budgetDescription TEXT DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS budgetStatus VARCHAR(50) DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS startDate DATE DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS endDate DATE DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS approvedBy VARCHAR(64) DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS approvedAt TIMESTAMP NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS totalBudgeted INT DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS totalActual INT DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS variance INT DEFAULT NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS variancePercent INT DEFAULT NULL;

-- === ESTIMATES TABLE ===
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS estimateNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS title VARCHAR(255) DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS issueDate TIMESTAMP NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS expiryDate TIMESTAMP NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS subtotal INT DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS taxAmount INT DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS discountAmount INT DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS total INT DEFAULT NULL;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS terms TEXT DEFAULT NULL;

-- === PRODUCTS TABLE ===
ALTER TABLE products ADD COLUMN IF NOT EXISTS costPrice INT DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS minStockLevel INT DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit VARCHAR(50) DEFAULT 'pcs';
ALTER TABLE products ADD COLUMN IF NOT EXISTS taxRate INT DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier VARCHAR(255) DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reorderLevel INT DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reorderQuantity INT DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS lastRestockDate TIMESTAMP NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS maxStockLevel INT DEFAULT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL;

-- === SERVICES TABLE ===
ALTER TABLE services ADD COLUMN IF NOT EXISTS hourlyRate INT DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS fixedPrice INT DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS unit VARCHAR(50) DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS taxRate INT DEFAULT 0;

-- === DEPARTMENTS TABLE ===
ALTER TABLE departments ADD COLUMN IF NOT EXISTS headId VARCHAR(64) DEFAULT NULL;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS budget INT DEFAULT NULL;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS defaultRole VARCHAR(100) DEFAULT NULL;

-- === OPPORTUNITIES TABLE ===
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS probability INT DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS expectedCloseDate DATE DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS actualCloseDate DATE DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS source VARCHAR(100) DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS winReason TEXT DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS lossReason TEXT DEFAULT NULL;
ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS stageMovedAt TIMESTAMP NULL;

-- === ACCOUNTS TABLE ===
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS accountCode VARCHAR(50) DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS accountType VARCHAR(100) DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS parentAccountId VARCHAR(64) DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS isActive TINYINT DEFAULT 1;

-- === ATTENDANCE TABLE ===
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS checkInTime TIME DEFAULT NULL;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS checkOutTime TIME DEFAULT NULL;
